name       : gnome-tetravex
version    : 3.36.2
release    : 4
source     :
    - https://download.gnome.org/sources/gnome-tetravex/3.36/gnome-tetravex-3.36.2.tar.xz : 0457aa672cdc17554d2c1df264c58776fa0e564801f4a7792e3ae342dfd0c661
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
description: |
    Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
