name       : gnome-tetravex
version    : 3.38.2
release    : 7
source     :
    - https://download.gnome.org/sources/gnome-tetravex/3.38/gnome-tetravex-3.38.2.tar.xz : 1fcdf10979b9a3526009d783a1c88a389918f360da4edb44fba25c71f186911b
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
description: |
    Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
