name       : gnome-tetravex
version    : 3.36.3
release    : 5
source     :
    - https://download.gnome.org/sources/gnome-tetravex/3.36/gnome-tetravex-3.36.3.tar.xz : fa46ffafd30998ddc22bba45750d47765ee1084fa465229d4308007264623378
license    : GPL-2.0-or-later
component  : games.puzzle
summary    : Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
description: |
    Tetravex is a simple puzzle where pieces must be positioned so that the same numbers are touching each other. Your game is timed, these times are stored in a system-wide scoreboard.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - itstool
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
